-- Apply once for databases created before 12/07/2026.
-- Safe to run again; fresh databases already include these columns in Database/schema.sql.
DELIMITER $$
DROP PROCEDURE IF EXISTS ApplyKhachThueIdentityVehicle$$
CREATE PROCEDURE ApplyKhachThueIdentityVehicle()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='KhachThue' AND COLUMN_NAME='NgayCapCCCD') THEN
        ALTER TABLE KhachThue ADD COLUMN NgayCapCCCD DATE NULL AFTER NgaySinh;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='KhachThue' AND COLUMN_NAME='NgheNghiep') THEN
        ALTER TABLE KhachThue ADD COLUMN NgheNghiep VARCHAR(150) NULL AFTER NgayCapCCCD;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='KhachThue' AND COLUMN_NAME='LoaiXe') THEN
        ALTER TABLE KhachThue ADD COLUMN LoaiXe VARCHAR(50) NULL AFTER NgheNghiep;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='KhachThue' AND COLUMN_NAME='BienSoXe') THEN
        ALTER TABLE KhachThue ADD COLUMN BienSoXe VARCHAR(30) NULL AFTER LoaiXe;
    END IF;
END$$
CALL ApplyKhachThueIdentityVehicle()$$
DROP PROCEDURE ApplyKhachThueIdentityVehicle$$
DELIMITER ;
